import type { Metadata } from "next"
import '@/assets/App.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id = 'app'>
          <h1>Yahtzee!</h1>
          {children}
        </div>
      </body>
    </html>
  )
}
